### ISSUE TITLE
Keyword Search deactivated and disappeared from Safari Extensions

### ISSUE THREAD

**Issue by alexanderroland** [arnemart/SafariKeywordSearch#27] opened 2022-03-16 11:21 UTC
Hi Arne,

I've been using your keyword search Safari macOS extension intensively over last few months since we spoke via e-mail.

Today, I noticed that:
1. The extension stopped working when attempting a keyword search.
2. The extension being gone from Safari's menu bar.
3. The extension not showing up anymore in Safari's settings > extensions. It seems like I uninstalled or never installed the extension.

However, the Keyword Search app is still in my Applications folder. When I open it, it prompts me 'You can enable the Keyword Search extension in Safari Extensions preferences'. When I click the 'Open Safari Extensions Preferences…' button, nothing happens or opens.

A uninstall and reinstall via App Store doesn't have any effect. Unfortunately I can't reproduce the error, but could try to delete any application support files if you can tell me a path to a folder in Library, in case these exist.

The iOS Safari extension still works and all my search settings still show up.

Thanks and best regards,
Alex

**Comment by shieldcy** [comment] 2022-04-12 13:15
I have the same issue. Could you please let us know what we can do to fix it?

Edit: I just noticed there is already a solution in the description

"There is a bug in Safari on macOS where extensions sometimes disappear. To fix it, quit Safari then copy this command and run it in the Terminal:
/System/Library/Frameworks/CoreServices.framework/Frameworks/LaunchServices.framework/Support/lsregister -f -R /Applications/Safari.app"

**Comment by porg** [comment] 2022-04-23 11:27
I too experienced the sudden deactivation of the SafariKeywordSearch extension somewhen the last 1-2 weeks:


![SafariKeywordSearch seems to got deactivated without notice by Safari update](https://user-images.githubusercontent.com/737143/164892492-7de4dc98-3dde-4431-b20b-ea89cb3abd8d.png)

**Comment by porg** [comment] 2022-04-23 11:35
## I tried the fix as in the description, but failed
1. Quitted Safari
2. Ran command line snippet. Returned null, so must have run correctly.
3. Launched Safari again.

❌ SafariKeywordSearch button still not there. Searches still not working.

## Then found out there's a missing step
4. In Safari open: Preferences > Extensions:
a) SafariKeywordSearch should show up again.
b) Re-activate the checkbox!

👉 From then on the button was there again and searching worked again.

I commited this important extra info to `Readme.md` in this [pull request](https://github.com/arnemart/SafariKeywordSearch/compare/main...porg:patch-1).

**Comment by porg** [comment] 2022-04-23 11:54
## One more observation
- After you successfully ran the fix (step 1-4)
- Open /Applications/Keyword Search.app/
- The button "Open Safari Extension Preferences…" works again and does just that! 👍 

![SafariKeywordSearch successfully opens Safari preferences again](https://user-images.githubusercontent.com/737143/164893435-081206ec-4c5d-4116-a440-40b0fe691f4d.png)

**Comment by porg** [comment] 2022-05-17 12:59
Dear original poster, the problem is known and there is as known fix for this in the [README.md](
https://github.com/arnemart/SafariKeywordSearch#did-the-extension-disappear-from-safari-on-macos).

Until my pull request to the Readme awaits approval, just use the instruction in [my post above](#issuecomment-1107456927).

And if successful please close with a comment here. Thanks.

**Comment by CartoonChess** [comment] 2022-07-16 08:46
I also encountered this problem and failed to notice the workaround in the readme as well. Thanks everyone :)

**Comment by porg** [comment] 2023-07-20 15:10
## Safari 16.5.1 → 16.5.2
- Again the extension got de-activated and invisible.
- Ran my fix again
  - Quitted Safari.
  - Ran the command again.
  - Restarted Safari
- This time something was different:
  - On my top window there was a slide-in notification which said something like 
  `Discovered new extension XYZ. Do you want to activate it?"`
  - Just clicked OKAY
  - Henceforth the extension worked again.
- So extension discovery has improved at least.
  - No need to manually go to Safari → Menu → Preferences →  Extensions.
  - But still good to know as a last resort to consult possibly.

**Closed as completed** 2023-08-10 08:27 UTC
